image: node:12.14.1

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - cd rose
          - yarn install
          - yarn compile
          - yarn lint
          - yarn test
          - cd ../rose-cli
          - yarn install
          - yarn compile
          - yarn lint
          - yarn test

definitions:
  caches:
    rose: rose/node_modules
    rose-cli: rose-cli/node_modules
