site:
  title: rose
  url: https://laurence-myers.github.io/rose/
  start_page: rose::index.adoc
content:
  edit_url: false
  sources:
  - url: ../
    branches: HEAD
    start_path: rose-docs/docs
ui:
  bundle:
    url: https://gitlab.com/laurence-myers/rose-antora-ui/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
