name: Rose CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    env:
      CI: true

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build and package rose
        run: |
          cd rose
          yarn install --frozen-lockfile
          yarn run check:all
          yarn run package
          cd package
          yarn link
      - name: Build and package rose-cli
        run: |
          cd rose-cli
          yarn install --frozen-lockfile
          yarn run check:all
          yarn run package
          cd package
          yarn link
      - name: Build rose-docs
        run: |
          cd rose-docs
          yarn run link:rose
          yarn install
          yarn run lint
          yarn run test
          yarn run start
      - name: Build rose-example
        run: |
          cd rose-example
          yarn run link:rose
          yarn install
          yarn run check:tsc
      - name: Upload test coverage report artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coverage-reports
          path: |
            rose/coverage/
            rose-cli/coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: rose/coverage/coverage-final.json,rose-cli/coverage/coverage-final.json
      - name: Publish docs to GitHub Pages
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: rose-docs/dist # The folder the action should deploy.
